text_field:
  base: "block w-full border rounded-md py-2 px-3 focus:outline-none"
  valid: "border-gray-300 focus:ring-indigo-500 focus:border-indigo-500"
  invalid: "pr-10 border-red-300 text-red-900 placeholder-red-300 focus:ring-red-500 focus:border-red-500"
label:
  base: "block text-sm font-medium text-gray-700"

